### ISSUE TITLE
Can the code still work now?

### ISSUE THREAD

**Issue by jluo41** [Madi-S/Multiprocessing-Asynchronous-Web-Scraping#1]
Hello, I have downloaded and tried your code today. But it cannot work with reporting the error "`bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?`"

I checked with `heatlhgrades` myself. It seems that the website have upgraded their page and only call elements with javascript. 

I tried several methods and didn't succeed. Can you try to make your code work again?

Thanks.

**Comment by Madi-S** [comment]
The issue you have written above is intertwined with your machine, probably it does not have "lxml" parser. I suggest you using "html.parser" instead. This will not make a big difference in speed.

Just change line 20 in parse_func.py from "soup = BeautifulSoup(html, 'lxml')" to "soup = BeautifulSoup(html, 'html.parser')"

I guess, I will rewrite the code in the foreseeable future.

**Comment by jluo41** [comment]
Thank you. You are right. I have fixed it.
